### ISSUE TITLE
How to pass arguments to phantomjs

### ISSUE THREAD

**Issue by mato75** [dflynn15/gulp-jasmine-phantom#50]
Example:

     $ phantomjs one.js http://www.google.com

How to do this with this library?

http://phantomjs.org/screen-capture.html

**Comment by dflynn15** [comment]
There is currently not a way to pass options to the `phantomjs` CLI. The purpose of this repository and tool is simply to be a test runner.
> A gulp plugin that runs Jasmine tests with either PhantomJS or minijasminenode2.

If you want to do anything additional I would highly encourage you looking into using [Gulp-Shell](https://www.npmjs.com/package/gulp-shell) to run `phantomjs` explicitly passing any options you need there.

However, if there is a compelling case in which you need to pass options to `phantom` in order to run tests that falls in the purpose and motivation of this plugin I would love to hear them. As always, feel free to put in a PR or fork the project to meet your own requirements. :+1:
